In [166]:
from __future__ import division
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pickle
import io

In [207]:
df = pd.DataFrame(pickle.load(open('clean_2015_data.pkl', 'rb')))

In [208]:
school_df = df[0:100]
school_df

,_projectid,_teacher_acctid,_schoolid,school_ncesid,school_latitude,school_longitude,school_city,school_state,school_zip,school_metro,...,students_reached,total_donations,num_donors,eligible_double_your_impact_match,eligible_almost_home_match,funding_status,date_posted,date_completed,date_thank_you_packet_mailed,date_expiration
0,7342bd01a2a7725ce033a179d22e382d,5c43ef5eac0f5857c266baa1ccfa3d3f,9e72d6f2f1e9367b578b6479aa5852b7,3.600097e+11,40.688454,-73.910432,Brooklyn,NY,11207,urban,...,0,251,1,f,f,completed,2002-09-13,2002-09-23,2003-01-27,2003-12-31
1,b56b502d25666e29550d107bf7e17910,57426949b47700ccf62098e1e9b0220c,4a06a328dd87bd29892d73310052f45f,3.600077e+11,40.770233,-73.950760,New York,NY,10075,NaN,...,0,125,1,f,f,completed,2002-09-16,2002-09-19,2002-12-19,2003-12-31
2,3a88a47f97bd0c9b7c6a745bcd831ce3,7a20087fac86232883537cab45c0a6c9,66d08b506d2f3c30dec9e6fdb03cc279,3.600122e+11,40.729763,-73.816925,Flushing,NY,11367,urban,...,0,2110,1,f,f,completed,2002-09-17,2003-03-17,2004-06-14,2003-12-31
3,0b8a4f8eb1822ab6dd5cd9ffb918ece3,e5d28482308e2007992ae8b358b31bce,9bc7d4d92193a453669b6e2a56128e87,3.600077e+11,40.701778,-74.011840,New York,NY,10004,urban,...,0,1241,1,f,f,completed,2002-09-17,2002-09-17,2003-12-18,2003-12-31
4,45235cb116b3b35cd86d1c3a63961d7d,214d75bd0e6ce3e7085278ddd8f26daa,f7f12dee0009e6f9afa301bcca9d5070,NaN,40.815018,-73.856094,Bronx,NY,10473,urban,...,0,83,1,f,f,completed,2002-09-17,2002-09-17,2004-01-28,2003-12-31
5,0b9607c9d3deb8b493653ed4f998fc38,454840ad7f58f2486203f73ee78ea2d5,0fad38af2fb328dd01bd3cef38ed42f2,3.600081e+11,40.809677,-73.939178,New York,NY,10037,urban,...,0,254,1,f,f,completed,2002-09-17,2002-09-23,2003-07-14,2003-12-31
6,702ef0896a72c258affa87e67b3462ef,e11a44441e604753223fb83ed1e5ef22,7e6d4e9ce212bbcc7ca208c3779095be,3.600103e+11,40.620422,-74.080750,Staten Island,NY,10304,urban,...,0,364,1,f,f,completed,2002-09-17,2002-11-05,2003-08-20,2003-12-31
7,3b5f4ae59d96f719dec6e72f1d10bd28,6504d611038542e638f54899caf35993,9ce97ca91e28b8493e9a911058f7dc24,3.600078e+11,40.791460,-73.970552,New York,NY,10025,urban,...,0,313,2,f,f,completed,2002-09-17,2002-12-17,2003-02-26,2003-12-31
8,a2b95aabc7e8518b58815d6855da95f2,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,0,454,1,f,f,completed,2002-09-17,2002-09-23,2002-11-19,2003-12-31
9,912e8cd1a736d2653db1fa91437a95af,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,380,1,f,f,completed,2002-09-17,2002-12-16,2003-08-01,2003-12-31
10,afdb477cc1ecfdce9996f3c122718732,e11a44441e604753223fb83ed1e5ef22,7e6d4e9ce212bbcc7ca208c3779095be,3.600103e+11,40.620422,-74.080750,Staten Island,NY,10304,urban,...,0,137,1,f,f,completed,2002-09-17,2002-09-23,2002-12-16,2003-12-31
11,97b50c1fef7c22945f16571f5ac5e562,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,367,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31
12,e24d8bb3d268a7c837077fa07c153063,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,0,0,f,f,completed,2002-09-17,2002-09-23,2003-08-04,2003-05-17
13,eb886a0ef1f498eb88f774947d3d02d7,b55921c6a3999b1f63e6ef69966b79aa,993e6202ffb7607f9b9ce616dd29140c,3.600091e+11,40.697353,-73.984512,Brooklyn,NY,11201,urban,...,0,577,1,f,f,completed,2002-09-17,2002-09-17,2002-12-03,2003-12-31
14,0d97d7543a766a07b3acf2c732844e85,d41b22314bd46c30150e50c4c78bc128,9bd4079c3ace16b8059eda8a42ce79fb,NaN,40.802662,-73.948097,NEW YORK,NY,10026,NaN,...,0,0,0,f,f,completed,2002-09-17,2002-09-23,2003-05-12,2003-12-31
15,016f03312995d5c89d6b348be4682166,9c0aa56b63b743454d6da9effcf122fc,bb0af5dac1b54693ba86ef63eacd6594,3.600076e+11,40.727826,-73.978721,New York,NY,10009,urban,...,0,205,1,f,f,completed,2002-09-17,2002-09-17,2002-12-02,2003-12-31
16,182f1734c1c6ec13d5544c17cfe838ec,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,363,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31
17,25afa366264801de896a9cdea0e64ae2,c0ff926aa5705245f70073bc7469e038,b5999531e0c1bb628ace29f3bd892e7c,3.600083e+11,40.850571,-73.933990,New York,NY,10033,urban,...,0,390,1,f,f,completed,2002-09-17,2002-10-03,2003-02-26,2003-12-31
18,2baeda61bab17a9ffdb5652e9c43512b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,508,1,f,f,completed,2002-09-17,2003-01-22,2003-08-11,2003-12-31
19,5821ee8eaab15a3bef73f118188c9505,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,0,320,1,f,f,completed,2002-09-17,2002-09-19,2002-11-19,2003-12-31
20,373107de43223f012a3b66ae409e8c32,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,298,1,f,f,completed,2002-09-17,2003-04-24,2004-01-28,2003-12-31
21,875534be2b101957c5083af745f68d50,84fd42b69d0db5710f09905939b366fe,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,0,374,1,f,f,completed,2002-09-17,2002-09-17,2003-01-03,2003-12-31
22,4338725801f6ce84e1d10b912ad21d91,b218f64064e174657336d229e2231962,52835c082f36edc0c90aff0c11a2e9b3,3.600079e+11,40.792306,-73.952037,New York,NY,10029,urban,...,0,772,3,f,f,completed,2002-09-17,2002-10-03,2003-08-08,2003-12-31
23,9caf2d27a918a9769bb1f4e345416f4b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,146,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31
24,6ba3b9d6d88a79dfa1acf5f3fcfa3776,0bebe562cdbcf7b14a1dd5f9793a7fd4,5307fce11b85e6ca6618448b1a3a075d,3.600085e+11,40.823649,-73.859879,Bronx,NY,10473,urban,...,0,267,1,f,f,completed,2002-09-17,2002-09-23,2003-08-24,2003-12-31
25,b0c7d8044cb170d9769079b5b2984538,f345f1ff1b7e98ce3d4bf67b2517eddc,74069ee85f6d41fd039befcb64107b5f,3.600086e+11,40.843352,-73.920440,Bronx,NY,10452,urban,...,0,132,1,f,f,completed,2002-09-17,2002-09-19,2003-07-17,2003-12-31
26,738da8a7dfd933a291bbc5d03949794a,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,278,1,f,f,completed,2002-09-17,2002-09-17,2003-01-30,2003-12-31
27,cf6275558534ca1b276b0d8d5130dd9a,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,0,264,1,f,f,completed,2002-09-17,2002-09-23,2003-02-26,2003-12-31
28,77e3b131ee90f011f937110e8e8e9cf4,b218f64064e174657336d229e2231962,52835c082f36edc0c90aff0c11a2e9b3,3.600079e+11,40.792306,-73.952037,New York,NY,10029,urban,...,0,900,1,f,f,completed,2002-09-17,2003-01-28,2004-01-30,2003-12-31
29,d25a7dd645bdfb4d702f177cef5e0d8e,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,317,1,f,f,completed,2002-09-17,2002-12-09,2003-08-01,2003-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,d11078ae3c97d7da47b19b22d39d8d33,2b6e71f317239196729820f00b90bbac,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,0,59,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31
71,f3375c6eb2b009e585e383e8cc7fb9df,b376a777ea77e924ae6e85cc2f4873f0,09a61be258ad61b1fd873ad0a2d1e541,3.600153e+11,40.597275,-73.948784,Brooklyn,NY,11229,urban,...,0,2362,1,f,f,completed,2002-09-19,2002-10-09,2002-12-10,2003-05-19
72,d3b401eb09fc7ee4efdbfa87986b4f30,b82e7411d87409afb2fc39a6174157c6,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,0,500,1,f,f,completed,2002-09-19,2003-04-18,2003-07-16,2003-12-31
73,02fa919306d0a181ed20888cca81f825,e3751e935d13de6b37864194955d1548,aab7207b58c29df564e721b9bff5f4d9,3.600121e+11,40.666550,-73.911084,Brooklyn,NY,11212,urban,...,0,426,1,f,f,completed,2002-09-19,2002-09-19,2002-12-16,2003-12-31
74,d41ddc9f4fb989243b6d229788a67594,8f8cdb340d839d9b104b046b4973a8ee,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,74,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31
75,0a5c1ae0fa84f429e4d9ced094c8da9a,658d734ecda2565fc33ab7f1e8da7435,e292eb8cc227208fe22952bdbaa27963,3.600103e+11,40.624836,-74.150597,Staten Island,NY,10303,urban,...,0,200,2,f,f,completed,2002-09-19,2002-09-23,2003-05-02,2003-12-31
76,e67cecdab63f131804e4699dfeca1b6f,696c8458f451fc8fbc4c7e470a03f4d4,3706b4dd4d68da21df7015cba19dbc02,3.600139e+11,40.806160,-73.948020,New York,NY,10027,urban,...,0,1067,1,f,f,completed,2002-09-19,2003-01-28,2003-07-21,2003-12-31
77,12561c981438681dad3c88c6b3135543,c7d000a93e3bd97624df1c420533a713,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,0,1099,2,f,f,completed,2002-09-19,2002-09-23,2003-02-13,2003-12-31
78,e8c3f04d4f0328ae284c8799c4f6e8b8,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,0,0,0,f,f,completed,2002-09-19,2002-09-19,2004-01-12,2003-12-31
79,1d7de428b9c8914f912fda5aa439d438,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,0,53,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31
80,f6070f5d7d293ed38cbaebb78c12a8aa,31367152c3ea88bfdf8a97848be8bd07,1bd8ff354157f9515669342576e6b8e5,3.600078e+11,40.799052,-73.964881,New York,NY,10025,urban,...,0,274,1,f,f,completed,2002-09-19,2002-09-19,2002-11-21,2003-12-31
81,3f02de31ad0ac6dbd30150d414aaea59,672bfbc2e05e5818b22398b4fd1ce9e7,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,785,1,f,f,completed,2002-09-19,2002-09-19,2003-02-21,2003-12-31
82,f9065c14b96ae492fb62924acb115521,d04fe28078bb087996351d7a6d0c20d1,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,0,250,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31
83,4d448db9634a09f9e81ef1fe72138c39,8860560acb3b3344b0c542a2405c2a41,ba54e9bfc11ea8b99c6b6517e3121101,3.600091e+11,40.688519,-73.971131,Brooklyn,NY,11205,urban,...,0,746,1,f,f,completed,2002-09-19,2003-04-07,2003-07-08,2003-12-31
84,02f1dc703bf33b84408e7913a09d101c,35e24c6b1f956a3ee72ecee1d304a4eb,8474659db4ef6cb7b9c1abab8e9378b9,3.600153e+11,40.604385,-73.955693,Brooklyn,NY,11229,urban,...,0,250,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31
85,56b5114f3bb47c247cb04e37f5394a7d,8ba8ae16f794598307095df5b5c67ce0,53e668061469bd44c45453aef8d88fdd,3.600077e+11,40.735510,-73.998921,New York,NY,10011,urban,...,0,480,3,f,f,completed,2002-09-19,2003-07-18,2004-01-20,2003-10-01
86,0dbaa7ed43f30640d99a1d95b7696a64,1aacfb91eb392114236f0c38fa44f27b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,285,2,f,f,completed,2002-09-19,2002-09-19,2003-02-26,2003-12-31
87,5f67686fed9f2e1ac83c6ffc95006444,0ecb3b20851102bf9aac6c3143920dea,7ead962f287a98571811204a0e1c9e42,3.600079e+11,40.792938,-73.947174,New York,NY,10029,urban,...,0,1243,5,f,f,completed,2002-09-19,2002-09-19,2002-12-16,2003-12-31
88,128e8542986bf571d509a1cd46cba1e9,1f4493b3d3fe4a611f3f4d21a249376a,1ae4695be589a36816188e2b301a0395,3.600077e+11,40.765517,-73.960090,New York,NY,10065,NaN,...,0,1610,1,f,f,completed,2002-09-19,2002-09-19,2003-01-03,2003-12-31
89,6d63ed299af4105930157e024852f457,84fd42b69d0db5710f09905939b366fe,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,0,385,1,f,f,completed,2002-09-19,2002-09-19,2003-01-03,2003-12-31
90,15f6fbbd115083517aa54b82e80a13c4,df8cde3ab0432f4c62fb7cdf096362eb,1615e71d5ed5e1f2dd4856b2668e35a3,3.600085e+11,40.825351,-73.873787,Bronx,NY,10472,urban,...,0,83,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31
91,74de37e5a09099b1601270e88909ec5f,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,283,1,f,f,completed,2002-09-19,2002-09-19,2003-01-30,2003-12-31
92,1c2365b548423cd64574e6e6da28913d,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,0,102,1,f,f,completed,2002-09-19,2002-09-19,2003-02-13,2003-12-31
93,78b724350aaece294a366f05b1b41499,225a1f3aced7d0a5642c494825234675,ffddd21ed1d58586b1f50bcedbd47750,3.600078e+11,40.806160,-73.948020,New York,NY,10027,urban,...,0,814,1,f,f,completed,2002-09-19,2003-04-24,2004-01-30,2003-12-31
94,1ce8ffb2d1543641e710d2294fd71ed5,12f612bc3919b270b0b4b89b6b6c909b,02f5dc94c4384eab7b4448003559070b,3.600102e+11,40.744753,-73.957952,Long Is City,NY,11109,urban,...,0,0,0,f,f,completed,2002-09-19,2002-09-19,2004-01-28,2003-12-31
95,78f0a1a42580973bb5a50d4c5279b3a6,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,0,244,1,f,f,completed,2002-09-19,2002-09-19,2003-05-12,2003-12-31
96,2e0eb3f25db079ce9d27c26f9a43f35b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,393,2,f,f,completed,2002-09-19,2002-09-19,2004-01-28,2003-12-31
97,867acebf5d6a364556dc763bb3b891cb,21a5742d5e6196ed64fae769c25c93ba,04f3cfd15642f95e296751a568089a9a,NaN,40.804859,-73.953697,New York,NY,10026,NaN,...,0,140,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31
98,39954c268478cdf9c609a907f9e841f7,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,0,395,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31
99,8a895ea9a4eb127999dad0f4bfbf9151,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,0,200,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31

In [203]:
def get_school_counts(row, df):
    filter = (df["_schoolid"] == row["_schoolid"])  & (df["date_completed"] < row["date_completed"])
    dc_count = df[filter]["date_completed"].count()
    print row['_schoolid']
    return pd.Series([dc_count])

In [204]:
%%time 
school_df[["school_previous_completed"]] = school_df.apply(lambda x : get_school_counts(x, school_df),axis=1)

00003e0fdd601b8ea0a6eb44057b9c5e
00003e0fdd601b8ea0a6eb44057b9c5e
00003e0fdd601b8ea0a6eb44057b9c5e
00003e0fdd601b8ea0a6eb44057b9c5e
00003e0fdd601b8ea0a6eb44057b9c5e
00003e0fdd601b8ea0a6eb44057b9c5e
00003e0fdd601b8ea0a6eb44057b9c5e
00003e0fdd601b8ea0a6eb44057b9c5e
00004e32a448b4832e1b993500bf0731
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
0004ffe3558fd70d939ad522b92447c8
000622b5ef4515b583da788f20be16ca
000630ab66464a738cab5036738075df
000630ab66464a738cab5036738075df
000630ab66464a738cab5036738075df
000630ab66464a738cab5036738075df
000630ab66464a738cab5036738075df
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
00064eac8b3d1f6dea8a07559922ed58
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
0006658276977eeefb5bc7b0c7399b5b
00073384a6b6c790563af323f0eb01b7
00073384a6b6c790563af323f0eb01b7
00073384a6b6c790563af323f0eb01b7
00073384a6b6c790563af323f0eb01b7
0009338d5927605c8a282b9b0e2d5aa0
0009f8a900cc0954f1db5802a8ce8ba3
0009f8a900cc0954f1db5802a8ce8ba3
0009f8a900cc0954f1db5802a8ce8ba3
000a21e544223a6cf1f3a79136275584
000a21e544223a6cf1f3a79136275584
000a21e544223a6cf1f3a79136275584
000a21e544223a6cf1f3a79136275584
000a21e544223a6cf1f3a79136275584
000a21e544223a6cf1f3a79136275584
000a21e544223a6cf1f3a79136275584
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
000a7d0f9cb24753fe909185806b574e
CPU times: user 238 ms, sys: 7.94 ms, total: 246 ms
Wall time: 249 ms

In [161]:
school_df

,_projectid,_teacher_acctid,_schoolid,school_ncesid,school_latitude,school_longitude,school_city,school_state,school_zip,school_metro,...,num_donors,eligible_double_your_impact_match,eligible_almost_home_match,funding_status,date_posted,date_completed,date_thank_you_packet_mailed,date_expiration,school_previous_projects,school_previous_completed
0,7342bd01a2a7725ce033a179d22e382d,5c43ef5eac0f5857c266baa1ccfa3d3f,9e72d6f2f1e9367b578b6479aa5852b7,3.600097e+11,40.688454,-73.910432,Brooklyn,NY,11207,urban,...,1,f,f,completed,2002-09-13,2002-09-23,2003-01-27,2003-12-31,0,1
1,b56b502d25666e29550d107bf7e17910,57426949b47700ccf62098e1e9b0220c,4a06a328dd87bd29892d73310052f45f,3.600077e+11,40.770233,-73.950760,New York,NY,10075,NaN,...,1,f,f,completed,2002-09-16,2002-09-19,2002-12-19,2003-12-31,0,0
2,3a88a47f97bd0c9b7c6a745bcd831ce3,7a20087fac86232883537cab45c0a6c9,66d08b506d2f3c30dec9e6fdb03cc279,3.600122e+11,40.729763,-73.816925,Flushing,NY,11367,urban,...,1,f,f,completed,2002-09-17,2003-03-17,2004-06-14,2003-12-31,0,0
3,0b8a4f8eb1822ab6dd5cd9ffb918ece3,e5d28482308e2007992ae8b358b31bce,9bc7d4d92193a453669b6e2a56128e87,3.600077e+11,40.701778,-74.011840,New York,NY,10004,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2003-12-18,2003-12-31,0,0
4,45235cb116b3b35cd86d1c3a63961d7d,214d75bd0e6ce3e7085278ddd8f26daa,f7f12dee0009e6f9afa301bcca9d5070,NaN,40.815018,-73.856094,Bronx,NY,10473,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2004-01-28,2003-12-31,0,0
5,0b9607c9d3deb8b493653ed4f998fc38,454840ad7f58f2486203f73ee78ea2d5,0fad38af2fb328dd01bd3cef38ed42f2,3.600081e+11,40.809677,-73.939178,New York,NY,10037,urban,...,1,f,f,completed,2002-09-17,2002-09-23,2003-07-14,2003-12-31,0,0
6,702ef0896a72c258affa87e67b3462ef,e11a44441e604753223fb83ed1e5ef22,7e6d4e9ce212bbcc7ca208c3779095be,3.600103e+11,40.620422,-74.080750,Staten Island,NY,10304,urban,...,1,f,f,completed,2002-09-17,2002-11-05,2003-08-20,2003-12-31,0,1
7,3b5f4ae59d96f719dec6e72f1d10bd28,6504d611038542e638f54899caf35993,9ce97ca91e28b8493e9a911058f7dc24,3.600078e+11,40.791460,-73.970552,New York,NY,10025,urban,...,2,f,f,completed,2002-09-17,2002-12-17,2003-02-26,2003-12-31,0,0
8,a2b95aabc7e8518b58815d6855da95f2,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-17,2002-09-23,2002-11-19,2003-12-31,0,5
9,912e8cd1a736d2653db1fa91437a95af,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-16,2003-08-01,2003-12-31,0,15
10,afdb477cc1ecfdce9996f3c122718732,e11a44441e604753223fb83ed1e5ef22,7e6d4e9ce212bbcc7ca208c3779095be,3.600103e+11,40.620422,-74.080750,Staten Island,NY,10304,urban,...,1,f,f,completed,2002-09-17,2002-09-23,2002-12-16,2003-12-31,0,0
11,97b50c1fef7c22945f16571f5ac5e562,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31,0,15
12,e24d8bb3d268a7c837077fa07c153063,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,f,f,completed,2002-09-17,2002-09-23,2003-08-04,2003-05-17,0,10
13,eb886a0ef1f498eb88f774947d3d02d7,b55921c6a3999b1f63e6ef69966b79aa,993e6202ffb7607f9b9ce616dd29140c,3.600091e+11,40.697353,-73.984512,Brooklyn,NY,11201,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2002-12-03,2003-12-31,0,0
14,0d97d7543a766a07b3acf2c732844e85,d41b22314bd46c30150e50c4c78bc128,9bd4079c3ace16b8059eda8a42ce79fb,NaN,40.802662,-73.948097,NEW YORK,NY,10026,NaN,...,0,f,f,completed,2002-09-17,2002-09-23,2003-05-12,2003-12-31,0,0
15,016f03312995d5c89d6b348be4682166,9c0aa56b63b743454d6da9effcf122fc,bb0af5dac1b54693ba86ef63eacd6594,3.600076e+11,40.727826,-73.978721,New York,NY,10009,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2002-12-02,2003-12-31,0,0
16,182f1734c1c6ec13d5544c17cfe838ec,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31,0,15
17,25afa366264801de896a9cdea0e64ae2,c0ff926aa5705245f70073bc7469e038,b5999531e0c1bb628ace29f3bd892e7c,3.600083e+11,40.850571,-73.933990,New York,NY,10033,urban,...,1,f,f,completed,2002-09-17,2002-10-03,2003-02-26,2003-12-31,0,0
18,2baeda61bab17a9ffdb5652e9c43512b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2003-01-22,2003-08-11,2003-12-31,0,20
19,5821ee8eaab15a3bef73f118188c9505,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-17,2002-09-19,2002-11-19,2003-12-31,0,0
20,373107de43223f012a3b66ae409e8c32,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2003-04-24,2004-01-28,2003-12-31,0,21
21,875534be2b101957c5083af745f68d50,84fd42b69d0db5710f09905939b366fe,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2003-01-03,2003-12-31,0,0
22,4338725801f6ce84e1d10b912ad21d91,b218f64064e174657336d229e2231962,52835c082f36edc0c90aff0c11a2e9b3,3.600079e+11,40.792306,-73.952037,New York,NY,10029,urban,...,3,f,f,completed,2002-09-17,2002-10-03,2003-08-08,2003-12-31,0,0
23,9caf2d27a918a9769bb1f4e345416f4b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31,0,15
24,6ba3b9d6d88a79dfa1acf5f3fcfa3776,0bebe562cdbcf7b14a1dd5f9793a7fd4,5307fce11b85e6ca6618448b1a3a075d,3.600085e+11,40.823649,-73.859879,Bronx,NY,10473,urban,...,1,f,f,completed,2002-09-17,2002-09-23,2003-08-24,2003-12-31,0,0
25,b0c7d8044cb170d9769079b5b2984538,f345f1ff1b7e98ce3d4bf67b2517eddc,74069ee85f6d41fd039befcb64107b5f,3.600086e+11,40.843352,-73.920440,Bronx,NY,10452,urban,...,1,f,f,completed,2002-09-17,2002-09-19,2003-07-17,2003-12-31,0,0
26,738da8a7dfd933a291bbc5d03949794a,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2003-01-30,2003-12-31,0,0
27,cf6275558534ca1b276b0d8d5130dd9a,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,1,f,f,completed,2002-09-17,2002-09-23,2003-02-26,2003-12-31,0,2
28,77e3b131ee90f011f937110e8e8e9cf4,b218f64064e174657336d229e2231962,52835c082f36edc0c90aff0c11a2e9b3,3.600079e+11,40.792306,-73.952037,New York,NY,10029,urban,...,1,f,f,completed,2002-09-17,2003-01-28,2004-01-30,2003-12-31,0,1
29,d25a7dd645bdfb4d702f177cef5e0d8e,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-09,2003-08-01,2003-12-31,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,d11078ae3c97d7da47b19b22d39d8d33,2b6e71f317239196729820f00b90bbac,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,0,0
71,f3375c6eb2b009e585e383e8cc7fb9df,b376a777ea77e924ae6e85cc2f4873f0,09a61be258ad61b1fd873ad0a2d1e541,3.600153e+11,40.597275,-73.948784,Brooklyn,NY,11229,urban,...,1,f,f,completed,2002-09-19,2002-10-09,2002-12-10,2003-05-19,0,0
72,d3b401eb09fc7ee4efdbfa87986b4f30,b82e7411d87409afb2fc39a6174157c6,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,1,f,f,completed,2002-09-19,2003-04-18,2003-07-16,2003-12-31,0,2
73,02fa919306d0a181ed20888cca81f825,e3751e935d13de6b37864194955d1548,aab7207b58c29df564e721b9bff5f4d9,3.600121e+11,40.666550,-73.911084,Brooklyn,NY,11212,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-12-16,2003-12-31,0,0
74,d41ddc9f4fb989243b6d229788a67594,8f8cdb340d839d9b104b046b4973a8ee,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,10,1
75,0a5c1ae0fa84f429e4d9ced094c8da9a,658d734ecda2565fc33ab7f1e8da7435,e292eb8cc227208fe22952bdbaa27963,3.600103e+11,40.624836,-74.150597,Staten Island,NY,10303,urban,...,2,f,f,completed,2002-09-19,2002-09-23,2003-05-02,2003-12-31,0,0
76,e67cecdab63f131804e4699dfeca1b6f,696c8458f451fc8fbc4c7e470a03f4d4,3706b4dd4d68da21df7015cba19dbc02,3.600139e+11,40.806160,-73.948020,New York,NY,10027,urban,...,1,f,f,completed,2002-09-19,2003-01-28,2003-07-21,2003-12-31,0,0
77,12561c981438681dad3c88c6b3135543,c7d000a93e3bd97624df1c420533a713,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,2,f,f,completed,2002-09-19,2002-09-23,2003-02-13,2003-12-31,1,4
78,e8c3f04d4f0328ae284c8799c4f6e8b8,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,0,f,f,completed,2002-09-19,2002-09-19,2004-01-12,2003-12-31,2,0
79,1d7de428b9c8914f912fda5aa439d438,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,2,0
80,f6070f5d7d293ed38cbaebb78c12a8aa,31367152c3ea88bfdf8a97848be8bd07,1bd8ff354157f9515669342576e6b8e5,3.600078e+11,40.799052,-73.964881,New York,NY,10025,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-11-21,2003-12-31,0,0
81,3f02de31ad0ac6dbd30150d414aaea59,672bfbc2e05e5818b22398b4fd1ce9e7,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2003-02-21,2003-12-31,10,1
82,f9065c14b96ae492fb62924acb115521,d04fe28078bb087996351d7a6d0c20d1,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,0,0
83,4d448db9634a09f9e81ef1fe72138c39,8860560acb3b3344b0c542a2405c2a41,ba54e9bfc11ea8b99c6b6517e3121101,3.600091e+11,40.688519,-73.971131,Brooklyn,NY,11205,urban,...,1,f,f,completed,2002-09-19,2003-04-07,2003-07-08,2003-12-31,0,1
84,02f1dc703bf33b84408e7913a09d101c,35e24c6b1f956a3ee72ecee1d304a4eb,8474659db4ef6cb7b9c1abab8e9378b9,3.600153e+11,40.604385,-73.955693,Brooklyn,NY,11229,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,0,0
85,56b5114f3bb47c247cb04e37f5394a7d,8ba8ae16f794598307095df5b5c67ce0,53e668061469bd44c45453aef8d88fdd,3.600077e+11,40.735510,-73.998921,New York,NY,10011,urban,...,3,f,f,completed,2002-09-19,2003-07-18,2004-01-20,2003-10-01,0,0
86,0dbaa7ed43f30640d99a1d95b7696a64,1aacfb91eb392114236f0c38fa44f27b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,2,f,f,completed,2002-09-19,2002-09-19,2003-02-26,2003-12-31,10,1
87,5f67686fed9f2e1ac83c6ffc95006444,0ecb3b20851102bf9aac6c3143920dea,7ead962f287a98571811204a0e1c9e42,3.600079e+11,40.792938,-73.947174,New York,NY,10029,urban,...,5,f,f,completed,2002-09-19,2002-09-19,2002-12-16,2003-12-31,0,0
88,128e8542986bf571d509a1cd46cba1e9,1f4493b3d3fe4a611f3f4d21a249376a,1ae4695be589a36816188e2b301a0395,3.600077e+11,40.765517,-73.960090,New York,NY,10065,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2003-01-03,2003-12-31,0,0
89,6d63ed299af4105930157e024852f457,84fd42b69d0db5710f09905939b366fe,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2003-01-03,2003-12-31,1,1
90,15f6fbbd115083517aa54b82e80a13c4,df8cde3ab0432f4c62fb7cdf096362eb,1615e71d5ed5e1f2dd4856b2668e35a3,3.600085e+11,40.825351,-73.873787,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,0,0
91,74de37e5a09099b1601270e88909ec5f,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2003-01-30,2003-12-31,10,1
92,1c2365b548423cd64574e6e6da28913d,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2003-02-13,2003-12-31,1,0
93,78b724350aaece294a366f05b1b41499,225a1f3aced7d0a5642c494825234675,ffddd21ed1d58586b1f50bcedbd47750,3.600078e+11,40.806160,-73.948020,New York,NY,10027,urban,...,1,f,f,completed,2002-09-19,2003-04-24,2004-01-30,2003-12-31,0,0
94,1ce8ffb2d1543641e710d2294fd71ed5,12f612bc3919b270b0b4b89b6b6c909b,02f5dc94c4384eab7b4448003559070b,3.600102e+11,40.744753,-73.957952,Long Is City,NY,11109,urban,...,0,f,f,completed,2002-09-19,2002-09-19,2004-01-28,2003-12-31,0,0
95,78f0a1a42580973bb5a50d4c5279b3a6,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2003-05-12,2003-12-31,2,0
96,2e0eb3f25db079ce9d27c26f9a43f35b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,2,f,f,completed,2002-09-19,2002-09-19,2004-01-28,2003-12-31,10,1
97,867acebf5d6a364556dc763bb3b891cb,21a5742d5e6196ed64fae769c25c93ba,04f3cfd15642f95e296751a568089a9a,NaN,40.804859,-73.953697,New York,NY,10026,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,0,0
98,39954c268478cdf9c609a907f9e841f7,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,1,0
99,8a895ea9a4eb127999dad0f4bfbf9151,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,2,0

In [12]:
%%time 
gg = school_df.groupby("_schoolid")  
df_ = pd.DataFrame()
for g, df in gg:
    df['school_previous_success'] = df.date_posted.map(lambda x: len(df[df.date_completed < x]))
    df['school_previous_projects'] = df.date_posted.map(lambda x: len(df[df.date_posted < x]))
    df['school_per_success'] = df.school_previous_success/df.school_previous_projects
    df_ = pd.concat([df_, df])

/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

CPU times: user 8.97 s, sys: 69.5 ms, total: 9.04 s
Wall time: 9.93 s

In [205]:
%%time
posted = school_df.set_index('date_posted').groupby('_schoolid').cumcount()
print posted

school_df['school_previous_posted'] = posted.values

date_posted
2014-08-14     0
2015-01-26     1
2015-02-23     2
2015-02-23     3
2015-03-29     4
2015-03-30     5
2015-04-27     6
2015-07-18     7
2014-03-08     0
2012-02-13     0
2012-05-11     1
2012-07-28     2
2012-08-23     3
2012-09-16     4
2012-11-12     5
2013-02-05     6
2013-02-11     7
2013-04-20     8
2013-07-13     9
2013-08-02    10
2013-08-04    11
2013-09-14    12
2013-12-27    13
2014-02-12    14
2014-06-10    15
2014-08-22    16
2014-08-27    17
2014-09-10    18
2014-09-24    19
2014-10-12    20
              ..
2012-09-02     0
2014-01-19     0
2014-08-25     1
2015-01-02     2
2011-01-10     0
2012-02-06     1
2013-08-29     2
2013-10-25     3
2014-02-01     4
2014-08-23     5
2014-09-14     6
2010-08-17     0
2010-08-20     1
2010-08-21     2
2010-11-26     3
2010-11-26     4
2010-12-01     5
2010-12-08     6
2010-12-13     7
2010-12-13     8
2011-01-17     9
2011-03-12    10
2011-07-10    11
2011-07-26    12
2011-07-26    13
2011-08-09    14
2011-08-21    15
2011-09-18    16
2012-09-26    17
2013-04-25    18
dtype: int64
CPU times: user 42.9 ms, sys: 2.59 ms, total: 45.5 ms
Wall time: 50.2 ms

/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [206]:
school_df

,_schoolid,date_posted,date_completed,RESP,school_previous_projects,school_previous_completed,school_previous_posted
694044,00003e0fdd601b8ea0a6eb44057b9c5e,2014-08-14,2014-12-08,1,0,0,0
801256,00003e0fdd601b8ea0a6eb44057b9c5e,2015-01-26,2015-03-19,1,1,2,1
813413,00003e0fdd601b8ea0a6eb44057b9c5e,2015-02-23,NaT,0,2,0,2
813653,00003e0fdd601b8ea0a6eb44057b9c5e,2015-02-23,2015-02-27,1,3,1,3
827868,00003e0fdd601b8ea0a6eb44057b9c5e,2015-03-29,2015-03-31,1,4,3,4
828674,00003e0fdd601b8ea0a6eb44057b9c5e,2015-03-30,2015-07-23,1,5,4,5
837186,00003e0fdd601b8ea0a6eb44057b9c5e,2015-04-27,NaT,0,6,0,6
863184,00003e0fdd601b8ea0a6eb44057b9c5e,2015-07-18,2015-08-09,1,7,5,7
643644,00004e32a448b4832e1b993500bf0731,2014-03-08,NaT,0,0,0,0
392796,0004ffe3558fd70d939ad522b92447c8,2012-02-13,2012-03-18,1,0,0,0
415049,0004ffe3558fd70d939ad522b92447c8,2012-05-11,NaT,0,1,0,1
428082,0004ffe3558fd70d939ad522b92447c8,2012-07-28,2012-08-10,1,2,1,2
435662,0004ffe3558fd70d939ad522b92447c8,2012-08-23,2012-09-01,1,3,2,3
447319,0004ffe3558fd70d939ad522b92447c8,2012-09-16,2012-10-08,1,4,3,4
473635,0004ffe3558fd70d939ad522b92447c8,2012-11-12,2012-12-22,1,5,4,5
497260,0004ffe3558fd70d939ad522b92447c8,2013-02-05,2013-04-04,1,6,6,6
499603,0004ffe3558fd70d939ad522b92447c8,2013-02-11,2013-02-18,1,7,5,7
515957,0004ffe3558fd70d939ad522b92447c8,2013-04-20,2013-05-20,1,8,7,8
534170,0004ffe3558fd70d939ad522b92447c8,2013-07-13,2013-09-09,1,9,10,9
539939,0004ffe3558fd70d939ad522b92447c8,2013-08-02,2013-08-05,1,10,8,10
540861,0004ffe3558fd70d939ad522b92447c8,2013-08-04,2013-09-06,1,11,9,11
564880,0004ffe3558fd70d939ad522b92447c8,2013-09-14,2013-12-08,1,12,11,12
618425,0004ffe3558fd70d939ad522b92447c8,2013-12-27,NaT,0,13,0,13
634025,0004ffe3558fd70d939ad522b92447c8,2014-02-12,NaT,0,14,0,14
670679,0004ffe3558fd70d939ad522b92447c8,2014-06-10,2014-10-06,1,15,15,15
701038,0004ffe3558fd70d939ad522b92447c8,2014-08-22,2014-08-23,1,16,12,16
709471,0004ffe3558fd70d939ad522b92447c8,2014-08-27,2014-09-03,1,17,13,17
727598,0004ffe3558fd70d939ad522b92447c8,2014-09-10,2014-09-19,1,18,14,18
743570,0004ffe3558fd70d939ad522b92447c8,2014-09-24,2014-12-31,1,19,16,19
756425,0004ffe3558fd70d939ad522b92447c8,2014-10-12,2015-01-07,1,20,17,20
...,...,...,...,...,...,...,...
439942,0009338d5927605c8a282b9b0e2d5aa0,2012-09-02,2012-10-21,1,0,0,0
625508,0009f8a900cc0954f1db5802a8ce8ba3,2014-01-19,2014-03-14,1,0,0,0
707810,0009f8a900cc0954f1db5802a8ce8ba3,2014-08-25,2014-12-18,1,1,1,1
790027,0009f8a900cc0954f1db5802a8ce8ba3,2015-01-02,2015-04-20,1,2,2,2
268919,000a21e544223a6cf1f3a79136275584,2011-01-10,2011-03-30,1,0,0,0
389363,000a21e544223a6cf1f3a79136275584,2012-02-06,2012-05-11,1,1,1,1
552979,000a21e544223a6cf1f3a79136275584,2013-08-29,2013-10-20,1,2,2,2
589589,000a21e544223a6cf1f3a79136275584,2013-10-25,2013-11-11,1,3,3,3
629757,000a21e544223a6cf1f3a79136275584,2014-02-01,2014-03-26,1,4,4,4
703746,000a21e544223a6cf1f3a79136275584,2014-08-23,2014-08-24,1,5,5,5
733403,000a21e544223a6cf1f3a79136275584,2014-09-14,2014-11-13,1,6,6,6
218440,000a7d0f9cb24753fe909185806b574e,2010-08-17,2010-09-17,1,0,1,0
219331,000a7d0f9cb24753fe909185806b574e,2010-08-20,2010-09-17,1,1,1,1
219742,000a7d0f9cb24753fe909185806b574e,2010-08-21,2010-09-10,1,2,0,2
253586,000a7d0f9cb24753fe909185806b574e,2010-11-26,2010-12-08,1,3,4,3
253634,000a7d0f9cb24753fe909185806b574e,2010-11-26,2010-12-04,1,4,3,4
254497,000a7d0f9cb24753fe909185806b574e,2010-12-01,2010-12-23,1,5,7,5
256995,000a7d0f9cb24753fe909185806b574e,2010-12-08,2010-12-10,1,6,5,6
260106,000a7d0f9cb24753fe909185806b574e,2010-12-13,2011-02-18,1,7,8,7
260397,000a7d0f9cb24753fe909185806b574e,2010-12-13,2010-12-22,1,8,6,8
271295,000a7d0f9cb24753fe909185806b574e,2011-01-17,NaT,0,9,0,9
288900,000a7d0f9cb24753fe909185806b574e,2011-03-12,NaT,0,10,0,10
315241,000a7d0f9cb24753fe909185806b574e,2011-07-10,2011-08-19,1,11,10,11
318677,000a7d0f9cb24753fe909185806b574e,2011-07-26,2011-08-16,1,12,9,12
318695,000a7d0f9cb24753fe909185806b574e,2011-07-26,2011-12-20,1,13,13,13
322406,000a7d0f9cb24753fe909185806b574e,2011-08-09,NaT,0,14,0,14
326723,000a7d0f9cb24753fe909185806b574e,2011-08-21,2011-09-26,1,15,11,15
336403,000a7d0f9cb24753fe909185806b574e,2011-09-18,2011-10-20,1,16,12,16
451078,000a7d0f9cb24753fe909185806b574e,2012-09-26,NaT,0,17,0,17
516966,000a7d0f9cb24753fe909185806b574e,2013-04-25,2013-05-02,1,18,14,18

In [176]:
school_df

,_projectid,_teacher_acctid,_schoolid,school_ncesid,school_latitude,school_longitude,school_city,school_state,school_zip,school_metro,...,num_donors,eligible_double_your_impact_match,eligible_almost_home_match,funding_status,date_posted,date_completed,date_thank_you_packet_mailed,date_expiration,posted,comp
0,7342bd01a2a7725ce033a179d22e382d,5c43ef5eac0f5857c266baa1ccfa3d3f,9e72d6f2f1e9367b578b6479aa5852b7,3.600097e+11,40.688454,-73.910432,Brooklyn,NY,11207,urban,...,1,f,f,completed,2002-09-13,2002-09-23,2003-01-27,2003-12-31,0,0
1,b56b502d25666e29550d107bf7e17910,57426949b47700ccf62098e1e9b0220c,4a06a328dd87bd29892d73310052f45f,3.600077e+11,40.770233,-73.950760,New York,NY,10075,NaN,...,1,f,f,completed,2002-09-16,2002-09-19,2002-12-19,2003-12-31,0,0
2,3a88a47f97bd0c9b7c6a745bcd831ce3,7a20087fac86232883537cab45c0a6c9,66d08b506d2f3c30dec9e6fdb03cc279,3.600122e+11,40.729763,-73.816925,Flushing,NY,11367,urban,...,1,f,f,completed,2002-09-17,2003-03-17,2004-06-14,2003-12-31,0,0
3,0b8a4f8eb1822ab6dd5cd9ffb918ece3,e5d28482308e2007992ae8b358b31bce,9bc7d4d92193a453669b6e2a56128e87,3.600077e+11,40.701778,-74.011840,New York,NY,10004,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2003-12-18,2003-12-31,0,0
4,45235cb116b3b35cd86d1c3a63961d7d,214d75bd0e6ce3e7085278ddd8f26daa,f7f12dee0009e6f9afa301bcca9d5070,NaN,40.815018,-73.856094,Bronx,NY,10473,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2004-01-28,2003-12-31,0,0
5,0b9607c9d3deb8b493653ed4f998fc38,454840ad7f58f2486203f73ee78ea2d5,0fad38af2fb328dd01bd3cef38ed42f2,3.600081e+11,40.809677,-73.939178,New York,NY,10037,urban,...,1,f,f,completed,2002-09-17,2002-09-23,2003-07-14,2003-12-31,0,0
6,702ef0896a72c258affa87e67b3462ef,e11a44441e604753223fb83ed1e5ef22,7e6d4e9ce212bbcc7ca208c3779095be,3.600103e+11,40.620422,-74.080750,Staten Island,NY,10304,urban,...,1,f,f,completed,2002-09-17,2002-11-05,2003-08-20,2003-12-31,0,0
7,3b5f4ae59d96f719dec6e72f1d10bd28,6504d611038542e638f54899caf35993,9ce97ca91e28b8493e9a911058f7dc24,3.600078e+11,40.791460,-73.970552,New York,NY,10025,urban,...,2,f,f,completed,2002-09-17,2002-12-17,2003-02-26,2003-12-31,0,0
8,a2b95aabc7e8518b58815d6855da95f2,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-17,2002-09-23,2002-11-19,2003-12-31,0,0
9,912e8cd1a736d2653db1fa91437a95af,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-16,2003-08-01,2003-12-31,0,0
10,afdb477cc1ecfdce9996f3c122718732,e11a44441e604753223fb83ed1e5ef22,7e6d4e9ce212bbcc7ca208c3779095be,3.600103e+11,40.620422,-74.080750,Staten Island,NY,10304,urban,...,1,f,f,completed,2002-09-17,2002-09-23,2002-12-16,2003-12-31,1,1
11,97b50c1fef7c22945f16571f5ac5e562,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31,1,1
12,e24d8bb3d268a7c837077fa07c153063,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,0,f,f,completed,2002-09-17,2002-09-23,2003-08-04,2003-05-17,2,2
13,eb886a0ef1f498eb88f774947d3d02d7,b55921c6a3999b1f63e6ef69966b79aa,993e6202ffb7607f9b9ce616dd29140c,3.600091e+11,40.697353,-73.984512,Brooklyn,NY,11201,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2002-12-03,2003-12-31,0,0
14,0d97d7543a766a07b3acf2c732844e85,d41b22314bd46c30150e50c4c78bc128,9bd4079c3ace16b8059eda8a42ce79fb,NaN,40.802662,-73.948097,NEW YORK,NY,10026,NaN,...,0,f,f,completed,2002-09-17,2002-09-23,2003-05-12,2003-12-31,0,0
15,016f03312995d5c89d6b348be4682166,9c0aa56b63b743454d6da9effcf122fc,bb0af5dac1b54693ba86ef63eacd6594,3.600076e+11,40.727826,-73.978721,New York,NY,10009,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2002-12-02,2003-12-31,0,0
16,182f1734c1c6ec13d5544c17cfe838ec,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31,3,3
17,25afa366264801de896a9cdea0e64ae2,c0ff926aa5705245f70073bc7469e038,b5999531e0c1bb628ace29f3bd892e7c,3.600083e+11,40.850571,-73.933990,New York,NY,10033,urban,...,1,f,f,completed,2002-09-17,2002-10-03,2003-02-26,2003-12-31,0,0
18,2baeda61bab17a9ffdb5652e9c43512b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2003-01-22,2003-08-11,2003-12-31,4,4
19,5821ee8eaab15a3bef73f118188c9505,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-17,2002-09-19,2002-11-19,2003-12-31,1,1
20,373107de43223f012a3b66ae409e8c32,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2003-04-24,2004-01-28,2003-12-31,5,5
21,875534be2b101957c5083af745f68d50,84fd42b69d0db5710f09905939b366fe,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2003-01-03,2003-12-31,0,0
22,4338725801f6ce84e1d10b912ad21d91,b218f64064e174657336d229e2231962,52835c082f36edc0c90aff0c11a2e9b3,3.600079e+11,40.792306,-73.952037,New York,NY,10029,urban,...,3,f,f,completed,2002-09-17,2002-10-03,2003-08-08,2003-12-31,0,0
23,9caf2d27a918a9769bb1f4e345416f4b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-16,2004-01-28,2003-12-31,6,6
24,6ba3b9d6d88a79dfa1acf5f3fcfa3776,0bebe562cdbcf7b14a1dd5f9793a7fd4,5307fce11b85e6ca6618448b1a3a075d,3.600085e+11,40.823649,-73.859879,Bronx,NY,10473,urban,...,1,f,f,completed,2002-09-17,2002-09-23,2003-08-24,2003-12-31,0,0
25,b0c7d8044cb170d9769079b5b2984538,f345f1ff1b7e98ce3d4bf67b2517eddc,74069ee85f6d41fd039befcb64107b5f,3.600086e+11,40.843352,-73.920440,Bronx,NY,10452,urban,...,1,f,f,completed,2002-09-17,2002-09-19,2003-07-17,2003-12-31,0,0
26,738da8a7dfd933a291bbc5d03949794a,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-09-17,2003-01-30,2003-12-31,7,7
27,cf6275558534ca1b276b0d8d5130dd9a,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,1,f,f,completed,2002-09-17,2002-09-23,2003-02-26,2003-12-31,0,0
28,77e3b131ee90f011f937110e8e8e9cf4,b218f64064e174657336d229e2231962,52835c082f36edc0c90aff0c11a2e9b3,3.600079e+11,40.792306,-73.952037,New York,NY,10029,urban,...,1,f,f,completed,2002-09-17,2003-01-28,2004-01-30,2003-12-31,1,1
29,d25a7dd645bdfb4d702f177cef5e0d8e,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-17,2002-12-09,2003-08-01,2003-12-31,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,d11078ae3c97d7da47b19b22d39d8d33,2b6e71f317239196729820f00b90bbac,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,0,0
71,f3375c6eb2b009e585e383e8cc7fb9df,b376a777ea77e924ae6e85cc2f4873f0,09a61be258ad61b1fd873ad0a2d1e541,3.600153e+11,40.597275,-73.948784,Brooklyn,NY,11229,urban,...,1,f,f,completed,2002-09-19,2002-10-09,2002-12-10,2003-05-19,0,0
72,d3b401eb09fc7ee4efdbfa87986b4f30,b82e7411d87409afb2fc39a6174157c6,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,1,f,f,completed,2002-09-19,2003-04-18,2003-07-16,2003-12-31,1,1
73,02fa919306d0a181ed20888cca81f825,e3751e935d13de6b37864194955d1548,aab7207b58c29df564e721b9bff5f4d9,3.600121e+11,40.666550,-73.911084,Brooklyn,NY,11212,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-12-16,2003-12-31,0,0
74,d41ddc9f4fb989243b6d229788a67594,8f8cdb340d839d9b104b046b4973a8ee,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,17,17
75,0a5c1ae0fa84f429e4d9ced094c8da9a,658d734ecda2565fc33ab7f1e8da7435,e292eb8cc227208fe22952bdbaa27963,3.600103e+11,40.624836,-74.150597,Staten Island,NY,10303,urban,...,2,f,f,completed,2002-09-19,2002-09-23,2003-05-02,2003-12-31,0,0
76,e67cecdab63f131804e4699dfeca1b6f,696c8458f451fc8fbc4c7e470a03f4d4,3706b4dd4d68da21df7015cba19dbc02,3.600139e+11,40.806160,-73.948020,New York,NY,10027,urban,...,1,f,f,completed,2002-09-19,2003-01-28,2003-07-21,2003-12-31,0,0
77,12561c981438681dad3c88c6b3135543,c7d000a93e3bd97624df1c420533a713,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,2,f,f,completed,2002-09-19,2002-09-23,2003-02-13,2003-12-31,3,3
78,e8c3f04d4f0328ae284c8799c4f6e8b8,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,0,f,f,completed,2002-09-19,2002-09-19,2004-01-12,2003-12-31,2,2
79,1d7de428b9c8914f912fda5aa439d438,6ace63f88c1e30fa52e57a6ea1999ecd,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,3,3
80,f6070f5d7d293ed38cbaebb78c12a8aa,31367152c3ea88bfdf8a97848be8bd07,1bd8ff354157f9515669342576e6b8e5,3.600078e+11,40.799052,-73.964881,New York,NY,10025,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-11-21,2003-12-31,0,0
81,3f02de31ad0ac6dbd30150d414aaea59,672bfbc2e05e5818b22398b4fd1ce9e7,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2003-02-21,2003-12-31,18,18
82,f9065c14b96ae492fb62924acb115521,d04fe28078bb087996351d7a6d0c20d1,39ddbff0638271cd2eb7793af1c91237,3.600081e+11,40.814840,-73.945051,New York,NY,10030,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,2,2
83,4d448db9634a09f9e81ef1fe72138c39,8860560acb3b3344b0c542a2405c2a41,ba54e9bfc11ea8b99c6b6517e3121101,3.600091e+11,40.688519,-73.971131,Brooklyn,NY,11205,urban,...,1,f,f,completed,2002-09-19,2003-04-07,2003-07-08,2003-12-31,1,1
84,02f1dc703bf33b84408e7913a09d101c,35e24c6b1f956a3ee72ecee1d304a4eb,8474659db4ef6cb7b9c1abab8e9378b9,3.600153e+11,40.604385,-73.955693,Brooklyn,NY,11229,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,0,0
85,56b5114f3bb47c247cb04e37f5394a7d,8ba8ae16f794598307095df5b5c67ce0,53e668061469bd44c45453aef8d88fdd,3.600077e+11,40.735510,-73.998921,New York,NY,10011,urban,...,3,f,f,completed,2002-09-19,2003-07-18,2004-01-20,2003-10-01,0,0
86,0dbaa7ed43f30640d99a1d95b7696a64,1aacfb91eb392114236f0c38fa44f27b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,2,f,f,completed,2002-09-19,2002-09-19,2003-02-26,2003-12-31,19,19
87,5f67686fed9f2e1ac83c6ffc95006444,0ecb3b20851102bf9aac6c3143920dea,7ead962f287a98571811204a0e1c9e42,3.600079e+11,40.792938,-73.947174,New York,NY,10029,urban,...,5,f,f,completed,2002-09-19,2002-09-19,2002-12-16,2003-12-31,0,0
88,128e8542986bf571d509a1cd46cba1e9,1f4493b3d3fe4a611f3f4d21a249376a,1ae4695be589a36816188e2b301a0395,3.600077e+11,40.765517,-73.960090,New York,NY,10065,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2003-01-03,2003-12-31,0,0
89,6d63ed299af4105930157e024852f457,84fd42b69d0db5710f09905939b366fe,5e4af81adba8db885dc6879c34cd5a57,3.600086e+11,40.832818,-73.911691,Bronx,NY,10456,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2003-01-03,2003-12-31,4,4
90,15f6fbbd115083517aa54b82e80a13c4,df8cde3ab0432f4c62fb7cdf096362eb,1615e71d5ed5e1f2dd4856b2668e35a3,3.600085e+11,40.825351,-73.873787,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,1,1
91,74de37e5a09099b1601270e88909ec5f,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2003-01-30,2003-12-31,20,20
92,1c2365b548423cd64574e6e6da28913d,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2003-02-13,2003-12-31,1,1
93,78b724350aaece294a366f05b1b41499,225a1f3aced7d0a5642c494825234675,ffddd21ed1d58586b1f50bcedbd47750,3.600078e+11,40.806160,-73.948020,New York,NY,10027,urban,...,1,f,f,completed,2002-09-19,2003-04-24,2004-01-30,2003-12-31,0,0
94,1ce8ffb2d1543641e710d2294fd71ed5,12f612bc3919b270b0b4b89b6b6c909b,02f5dc94c4384eab7b4448003559070b,3.600102e+11,40.744753,-73.957952,Long Is City,NY,11109,urban,...,0,f,f,completed,2002-09-19,2002-09-19,2004-01-28,2003-12-31,0,0
95,78f0a1a42580973bb5a50d4c5279b3a6,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2003-05-12,2003-12-31,4,4
96,2e0eb3f25db079ce9d27c26f9a43f35b,0c2d4535f03991165dc72092840d672b,cabcc3ed826056c3969a8a99c5aeeaf6,3.600085e+11,40.829224,-73.856899,Bronx,NY,10472,urban,...,2,f,f,completed,2002-09-19,2002-09-19,2004-01-28,2003-12-31,21,21
97,867acebf5d6a364556dc763bb3b891cb,21a5742d5e6196ed64fae769c25c93ba,04f3cfd15642f95e296751a568089a9a,NaN,40.804859,-73.953697,New York,NY,10026,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,0,0
98,39954c268478cdf9c609a907f9e841f7,1d4d8a42730dbb66af1ebb6ab37456b7,768dab263f87881fe7c68ffb3965df7c,3.600083e+11,40.841216,-73.938605,New York,NY,10032,urban,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,2,2
99,8a895ea9a4eb127999dad0f4bfbf9151,55c29624cdb74469ff2e3db06eaa10a1,6f0382325857ae3469d04800c470c509,NaN,40.753002,-73.992409,New York,NY,10018,NaN,...,1,f,f,completed,2002-09-19,2002-09-19,2002-09-19,2003-12-31,5,5

In [179]:
final_df = pd.DataFrame(pickle.load(open('clean_data_with_features.pkl', 'rb')))

In [184]:
df = final_df[['_schoolid', 'date_posted', 'date_completed', 'RESP', 'school_previous_projects', 'school_previous_completed']]
df = df.sort(['_schoolid', 'date_posted'])
df

,_schoolid,date_posted,date_completed,RESP,school_previous_projects,school_previous_completed
694044,00003e0fdd601b8ea0a6eb44057b9c5e,2014-08-14,2014-12-08,1,0,0
801256,00003e0fdd601b8ea0a6eb44057b9c5e,2015-01-26,2015-03-19,1,1,1
813413,00003e0fdd601b8ea0a6eb44057b9c5e,2015-02-23,NaT,0,2,2
813653,00003e0fdd601b8ea0a6eb44057b9c5e,2015-02-23,2015-02-27,1,3,3
827868,00003e0fdd601b8ea0a6eb44057b9c5e,2015-03-29,2015-03-31,1,4,4
828674,00003e0fdd601b8ea0a6eb44057b9c5e,2015-03-30,2015-07-23,1,5,5
837186,00003e0fdd601b8ea0a6eb44057b9c5e,2015-04-27,NaT,0,6,6
863184,00003e0fdd601b8ea0a6eb44057b9c5e,2015-07-18,2015-08-09,1,7,7
643644,00004e32a448b4832e1b993500bf0731,2014-03-08,NaT,0,0,0
392796,0004ffe3558fd70d939ad522b92447c8,2012-02-13,2012-03-18,1,0,0
415049,0004ffe3558fd70d939ad522b92447c8,2012-05-11,NaT,0,1,1
428082,0004ffe3558fd70d939ad522b92447c8,2012-07-28,2012-08-10,1,2,2
435662,0004ffe3558fd70d939ad522b92447c8,2012-08-23,2012-09-01,1,3,3
447319,0004ffe3558fd70d939ad522b92447c8,2012-09-16,2012-10-08,1,4,4
473635,0004ffe3558fd70d939ad522b92447c8,2012-11-12,2012-12-22,1,5,5
497260,0004ffe3558fd70d939ad522b92447c8,2013-02-05,2013-04-04,1,6,6
499603,0004ffe3558fd70d939ad522b92447c8,2013-02-11,2013-02-18,1,7,7
515957,0004ffe3558fd70d939ad522b92447c8,2013-04-20,2013-05-20,1,8,8
534170,0004ffe3558fd70d939ad522b92447c8,2013-07-13,2013-09-09,1,9,9
539939,0004ffe3558fd70d939ad522b92447c8,2013-08-02,2013-08-05,1,10,10
540861,0004ffe3558fd70d939ad522b92447c8,2013-08-04,2013-09-06,1,11,11
564880,0004ffe3558fd70d939ad522b92447c8,2013-09-14,2013-12-08,1,12,12
618425,0004ffe3558fd70d939ad522b92447c8,2013-12-27,NaT,0,13,13
634025,0004ffe3558fd70d939ad522b92447c8,2014-02-12,NaT,0,14,14
670679,0004ffe3558fd70d939ad522b92447c8,2014-06-10,2014-10-06,1,15,15
701038,0004ffe3558fd70d939ad522b92447c8,2014-08-22,2014-08-23,1,16,16
709471,0004ffe3558fd70d939ad522b92447c8,2014-08-27,2014-09-03,1,17,17
727598,0004ffe3558fd70d939ad522b92447c8,2014-09-10,2014-09-19,1,18,18
743570,0004ffe3558fd70d939ad522b92447c8,2014-09-24,2014-12-31,1,19,19
756425,0004ffe3558fd70d939ad522b92447c8,2014-10-12,2015-01-07,1,20,20
...,...,...,...,...,...,...
229264,ffff9bb21699f79266cc7cbc208890a0,2010-09-15,2010-09-15,1,1,1
535022,ffff9bb21699f79266cc7cbc208890a0,2013-07-16,2013-09-02,1,2,2
628890,ffff9bb21699f79266cc7cbc208890a0,2014-01-30,NaT,0,3,3
628929,ffff9bb21699f79266cc7cbc208890a0,2014-01-30,NaT,0,4,4
629031,ffff9bb21699f79266cc7cbc208890a0,2014-01-30,NaT,0,5,5
629054,ffff9bb21699f79266cc7cbc208890a0,2014-01-30,NaT,0,6,6
629139,ffff9bb21699f79266cc7cbc208890a0,2014-01-30,NaT,0,7,7
182605,ffffc2e1225ac40a3ace9b8562115c9b,2010-01-15,2010-03-22,1,0,0
212832,ffffc2e1225ac40a3ace9b8562115c9b,2010-07-26,NaT,0,1,1
340253,ffffc2e1225ac40a3ace9b8562115c9b,2011-09-27,2011-10-04,1,2,2
349260,ffffc2e1225ac40a3ace9b8562115c9b,2011-10-25,2011-12-05,1,3,3
363624,ffffc2e1225ac40a3ace9b8562115c9b,2011-12-09,2011-12-16,1,4,4
370328,ffffc2e1225ac40a3ace9b8562115c9b,2011-12-31,2012-03-17,1,5,5
397340,ffffc2e1225ac40a3ace9b8562115c9b,2012-02-27,2012-03-14,1,6,6
433000,ffffc2e1225ac40a3ace9b8562115c9b,2012-08-15,2012-08-29,1,7,7
434376,ffffc2e1225ac40a3ace9b8562115c9b,2012-08-19,2012-08-20,1,8,8
442043,ffffc2e1225ac40a3ace9b8562115c9b,2012-09-05,NaT,0,9,9
445453,ffffc2e1225ac40a3ace9b8562115c9b,2012-09-11,2012-09-13,1,10,10
451664,ffffc2e1225ac40a3ace9b8562115c9b,2012-09-27,2012-12-31,1,11,11
480995,ffffc2e1225ac40a3ace9b8562115c9b,2012-12-08,NaT,0,12,12
489736,ffffc2e1225ac40a3ace9b8562115c9b,2013-01-09,2013-01-09,1,13,13
515230,ffffc2e1225ac40a3ace9b8562115c9b,2013-04-14,2013-04-16,1,14,14
535511,ffffc2e1225ac40a3ace9b8562115c9b,2013-07-18,2013-09-05,1,15,15
555192,ffffc2e1225ac40a3ace9b8562115c9b,2013-09-01,2013-09-04,1,16,16
610321,ffffc2e1225ac40a3ace9b8562115c9b,2013-12-01,2013-12-22,1,17,17
626133,ffffc2e1225ac40a3ace9b8562115c9b,2014-01-20,2014-02-21,1,18,18
733191,ffffc2e1225ac40a3ace9b8562115c9b,2014-09-14,2014-10-01,1,19,19
793649,ffffc2e1225ac40a3ace9b8562115c9b,2015-01-14,2015-02-13,1,20,20
812335,ffffc2e1225ac40a3ace9b8562115c9b,2015-02-20,2015-03-29,1,21,21
836203,ffffc2e1225ac40a3ace9b8562115c9b,2015-04-23,2015-05-31,1,22,22

In [182]:
final_df.columns.values.tolist()

['_projectid',
 '_teacher_acctid',
 '_schoolid',
 'school_ncesid',
 'school_latitude',
 'school_longitude',
 'school_city',
 'school_state',
 'school_zip',
 'school_metro',
 'school_district',
 'school_county',
 'school_charter',
 'school_magnet',
 'school_year_round',
 'school_nlns',
 'school_kipp',
 'school_charter_ready_promise',
 'teacher_prefix',
 'teacher_teach_for_america',
 'teacher_ny_teaching_fellow',
 'primary_focus_subject',
 'primary_focus_area',
 'secondary_focus_subject',
 'secondary_focus_area',
 'resource_type',
 'poverty_level',
 'grade_level',
 'vendor_shipping_charges',
 'sales_tax',
 'payment_processing_charges',
 'fulfillment_labor_materials',
 'total_price_excluding_optional_support',
 'total_price_including_optional_support',
 'students_reached',
 'total_donations',
 'num_donors',
 'eligible_double_your_impact_match',
 'eligible_almost_home_match',
 'funding_status',
 'date_posted',
 'date_completed',
 'date_thank_you_packet_mailed',
 'date_expiration',
 'RESP',
 'month',
 'quarter',
 'year',
 'time_to_expire',
 'amount_optional_support',
 'optional_support',
 'per_optional_support',
 'school_previous_projects',
 'school_previous_completed',
 'teacher_previous_projects',
 'teacher_previous_completed']